## markdown 语法
### 1.字体
文字后面额外加两个空格也能换行  
我是**粗体**  
我是*斜体*  
我是~~删除线~~

### 2.列表
##### 无序列表
- 我是列表第一项
- 我是列表第二项
##### 有序列表
1. 我是列表第一项
2. 我是列表第二项

### 3.引用
#### 引用段落
> 穿过长长的县道，就是雪国。夜的底色变为银白。火车在信号所停下。
#### 直接放链接
https://www.bilibili.com/video/BV1eN411Y7kt/?spm_id_from=333.1007.tianma.1-1-1.click&vd_source=62a21f026fe60108faad8418b1f5996d
#### 给链接取个名字
[马鲛岛失踪案](https://www.bilibili.com/video/BV1eN411Y7kt/?spm_id_from=333.1007.tianma.1-1-1.click&vd_source=62a21f026fe60108faad8418b1f5996d)
#### 图片
![郊区风景](https://www.5tu.cn/attachments/image_files/month_1910/2019010170704111224.jpg)

### 4.插入代码
我们通过`import math`来导入math库

代码段落：
```python
import math
print("hello world")
print(math.pi)
```

## Latex语法
### 1.公式
这是一个公式： $y=x+3$

下面是独占一行的公式： $$y=x+3$$
### 2.运算符号
$$y+x$$
$$y-x$$
$$x \times y$$
$$x \div y$$
$$ x^{2 \times e} $$
$$ \sqrt[3]{x} $$
$$ x_{i,t} $$
$$ \sum {(x^2+y^2)} $$
$$ \frac{x+y}{x \times y} $$

<font color="#dd000">Latex上下标、求根、求和等运算默认只作用于一个字符，如果你想作用于多个字符就用{}括起来</font>


# numpy用于数据处理

numpy是一个第三方库需要到终端中安装在使用
安装方法：
> pip3 install numpy  # MacOs  
> pip install numpy

## 1.array

1.1
numpy的列表与python列表的不同：  
numpy列表里面需要时同一种类型的数据，如果输入不同的类型数据numpy会强行把你输入的数据统一为一种类型；而python列表里面可以是不同种类的数据


In [3]:
import numpy as np

### 1.1 构建数组

#### 1.1.1 手动输入数组

In [3]:
arr1 = np.array([1, 2, 3])  # numpy数组中的元素必须是同一种类型，字符串、整数、浮点数、布尔值等
arr1

array([1, 2, 3])

In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(arr1.ndim)

1


In [12]:
print(arr2.shape)  
# shape会返回一个元组，元组长度表示维数；如果是一位数组第一个数是列数，如果是二维数组第一个数是行数，第二个数是列数

(2, 3)


In [14]:
print(arr2.size)  # 返回数组里面元素总个数

6


In [16]:
print(arr2.dtype)  # .dtype返还数组里面元素类型

int64


#### 1.1.2 以数列生成数组

In [25]:
np.zeros(3, int)  # 生成一维数组，第二个参数为数据类型，如果没有输入就默认是浮点数

array([0, 0, 0])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.arange(5, 9, 1)  # a range 表示针对array的range方法

array([5, 6, 7, 8])

#### 1.1.1 和 1.1.2练习

写出导入numpy的语句，并命名为np。

In [31]:
import numpy as np

创建一个 `arr1` 的一维数组，里面元素为整数，创建后输出 arr1。 

In [34]:
arr1 = np.array([1, 2, -4, 5, 3])
arr1

array([ 1,  2, -4,  5,  3])

创建一个名为 ``arr2` 的二维数组，创建后输出arr2

In [38]:
arr2 = np.array([[1, 2, 3], [2, 4, 6]])
arr2

array([[1, 2, 3],
       [2, 4, 6]])

分别打印出 `arr1` 和 `arr2` 的维度、形状、元素数量、元素类型


In [40]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

1
(5,)
5
int64
2
(2, 3)
6
int64


创建一个名为 `arr_all_0` 的一维数组，里面元素6个0，并输出

In [42]:
arr_all_0 = np.zeros(6)
arr_all_0

array([0., 0., 0., 0., 0., 0.])

创建一个名为 `arr_all_1` 的一维数组，里面元素全为1

In [44]:
arr_all_1 = np.ones(6)
arr_all_1

array([1., 1., 1., 1., 1., 1.])

创建一个名为arr_even的数组，10到20的所以偶数构成包括20

In [45]:
arr_even = np.arange(10, 21, 2)
arr_even

array([10, 12, 14, 16, 18, 20])

### 1.2  对数组进行操作

#### 1.2.1 连接数组

##### 1.2.1.1 横向连接数组

In [49]:
arr1 = np.array([1, 2, 3])
arr2 = np.zeros(3)
arr_12 = np.concatenate([arr1, arr2])
arr_12  # 会把array里面数据类型统一

array([1., 2., 3., 0., 0., 0.])

In [57]:
print(arr_12)

[1. 2. 3. 0. 0. 0.]


##### 两个一维数组连接为一个二维数组

In [56]:
arr_2d = np.stack((arr1, arr2))
arr_2d

array([[1., 2., 3.],
       [0., 0., 0.]])

python中：  
list = [1, 3, 5, 2, 4]

sorted()函数，函数会生成一个新的列表  
```python
list1 = sorted(list)  
print(list1)
```
> [1, 2, 3, 4, 5]

.sort()方法，方法是对原来的进行修改  
```python
list.sort() 
print(list) 
```
> [1, 2, 3, 4, 5]


#### 1.2.2 数组内元素排序：一维

In [58]:
import numpy as np

In [59]:
arr1 = np.array([1, 5, 3, 2, 9])
print(np.sort(arr1))
print(arr1)

[1 2 3 5 9]
[1 5 3 2 9]


In [61]:
arr2 = np.array([9, 6, 5, 7, 1])
print(arr2.sort())  # 什么都不返回值是对原来的数组进行操作
print(arr2)

None
[1 5 6 7 9]


### 1.3 数组索引

#### 1.3.1 单个索引

In [4]:
arr1 = np.array([4, 6, 3, 2, 1])
print(arr1[1])

6


#### 1.3.2 切片索引

In [65]:
print(arr1[1: 4])  # 切片索引索引号是左闭右开的，切片出的会形成数组

[6 3 2]


### 1.4 数组的运算：线性代数运算

In [66]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 5, 6, 7])
print(arr1 + arr2)
print(arr1 * 3)

[ 5  7  9 11]
[ 3  6  9 12]


In [5]:
print(arr1.max())
print(arr1.min())
print(arr1.mean())
print(arr1.sum())

6
1
3.2
16


In [7]:
arr1 > 5  # 会返回一个布尔值组成的数组

array([False,  True, False, False, False])

In [71]:
arr3 = np.array([3, 5, 9, 10, 78])
arr3[arr3 > 11]

array([78])

In [72]:
arr3[(arr3 > 5) & (arr3 <11)]  # 里面还可以加逻辑运算

array([ 9, 10])

<font color="#dd000"> numpy里面与 或 非对应符号为& | ~</font>

1.3 和 1.4数组操作练习

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 3, 2, 4, 9])
arr2 = np.zeros(3)
arr3 = np.ones(5)

创建数组arr4，包括arr1、arr2、arr3中的所有元素

In [5]:
arr4 = np.concatenate([arr1, arr2, arr3])
arr4

array([1., 3., 2., 4., 9., 0., 0., 0., 1., 1., 1., 1., 1.])

更改arr1，对arr1里的元素进行排序，并输出排序后的结果。

In [14]:
arr1.sort()
arr1

array([1, 2, 3, 4, 9])

用两种方法打印arr1的第三个元素

In [12]:
print(arr1[2])
print(arr1[-3])

3
3


输出arr1第2个到第4个元素组成的

In [13]:
print(arr1[1: 4])

[2 3 4]


输出arr1和arr3相同位置元素相加后组成的数组

In [19]:
arr_12 = arr1 + arr3
arr_12

array([ 2.,  3.,  4.,  5., 10.])

输出arr1的各个元素乘以-5后组成的数组

In [18]:
print(arr1 * (-5))

[ -5 -10 -15 -20 -45]


打印出arr1数组的最小值、最大值、和、平均值

In [21]:
print(arr1.min())
print(arr1.max())
print(arr1.sum())
print(arr1.mean())

1
9
19
3.8


筛选出arr1数组里面所有小于1或大于2的数字，并打印出来

In [27]:
print(arr1[(arr1 < 1) | (arr1 > 2)])

[3 4 9]


In [29]:
arr1 < 1

array([False, False, False, False, False])

In [31]:
arr1 > 2

array([False, False,  True,  True,  True])

In [32]:
arr1[arr1 > 2]

array([3, 4, 9])